---
title: "Conducting a Fairness Assessment"
format: html
jupyter: python3
editor: visual
---

# Introduction

Over the past few years AI and machine learning models have been developed in a wide range of industries such as lending, hiring healthcare and education. Some of these models have been given autonomy to or are used to aid humans make decisions that have significant real world effects. For example, denying or accepting loan applications based on how likely a borrower is to repay their debt or whether to release or detain an individual in custody based on if they are going to show up to court. In the coming year we are only going to see the use and influence of these models increase.

Because these models can have outsized effects on a person's life there is growing concern about whether models will treat every person fairly. There are already many cases of a model performing differently across groups defined by characteristics such as race or gender. There is a now infamous example where amazon created a model that penalized job applicants that mentioned the word woman in their resume. When differences lead to unequal outcomes such as the previous example we can say that the model is unfair. Work to solve this problem has led to the development of algorithmic fairness and many attempts to define and minimize unfairness [@mitchellAlgorithmicFairnessChoices2021].

The rest of this guide will cover how you can use the Fairlearn framework to evaluate the fairness of regression and classification models. However it is important to remember that fairness problems are not caused by models themselves. Models are just a reflection of the decisions we make, such as what data to use in the model, what we choose to predict from the model and how we apply the model. Tools like Fairlearn can be used to help work towards more fair models but can not make a perfectly fair model.

Going forward it is recommend that you have some knowledge of the basics of regression or classification machine learn algorithms, understanding python of the sklearn library and access to some way to execute jupyter notebook segments 

# Performing a Fairness Assessment

A fairness assessment is a way to examine how a machine learning model impacts different groups of people. It gives you a system to answer which groups might be negatively affected by the model and in what ways?

A fairness assessment follows four simple steps:

1.  Identify the types of harms that might occur
2.  Identify the groups that could experience those harms
3.  Quantify the harms using measurable metrics
4.  Compare Compareing Quantified Harm across groups

## Identifying Types of Harms

The first step in this process is to think about the different kinds of harm the model might create. There are many types of harm but we will only cover some of the most common that you will see.

Allocation Harm is when an AI model will grant or deny resources or opportunity. For example a model that gives out loans to individuals or a model that is used to decide admission to a university are at risk of Allocation Harm.

Quality of service harms when the model will work better for one group of people than another. Examples of this are speech to text which might struggle to properly denote what a regional accent is saying or face recognition misidentifying people of a certain race at a higher rate.

Stereotyping harm and erasure harm or more common in LLMs then regression or classification models unlike the previous two types of harm. Stereotyping harms can happen when a negative stereotype is reinforced by a model. Google auto complete is an example where a model is at risk of Stereotyping harm. Erasure harm is when a model behaves as if the group or their work does not exist. Asking an LLM for a biography of Alan Turing and it not giving time to talk about his sexuality would be a type of erasure harm.

It is important to remember that any model can demonstrate more than one type of harm and the types of harm we discussed are not mutually exclusive.

## Identify the Groups That Might Be Harmed

Now that we have identified the possible harms that the model could cause we need to Identify what groups of people would be affected by that harm. In many cases these will be groups who have been historically marginalized based on gender, race or ethnicity.

However the groups you Identify may not be the traditional ones depending on the application of the model. Going back to the speech to text example, we could identify groups such as regional dialects/accents or non native speakers of a language that might be treated unfairly by the model. This is to say that the groups that might be harmed by the model will depend greatly on the application of the model.

It is critical to consider how groups could intersect to reveal harm. If you think along only one axis such as race or gender you could overlook when an intersection of the groups is experiencing harm. An example is when asian men experience worse harm then either asians or men on average.

## Quantify Harms

Once the possible harms and groups are identified the next step is to measure those harms using a metric. If we use lending as an example we might measure how often qualified candidates are incorrectly rejected. We could capture this by using the False negative rate which is just a measure of applicants who were mistakenly rejected while being qualified for a loan. If we were to look at speech to text we would measure the word error rate or the number of transcription mistakes divided by the number of words in total. If we were to find a difference in these metrics across different groups this may indicate a fairness problem.

This is where the Fairlearn library becomes a helpful tool for us to use. Using the Fairlearn’s Metricframe object we can assess the disaggregated metrics of the data. Instead of only looking at how a model's overall performance disaggregated metrics will allow us to see if the model behaves differently for different populations. Ideally the different populations you would use the Metricframe to analyze are the ones that you identified in step two.

We have three pieces of information

-   True labels (y_true)
-   Model predictions (y_pred)
-   Group membership (sf_data)

```{python}
y_true = [0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0]

y_pred = [0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1]

sf_data = [
    'female', 'female', 'male', 'female', 'female',
    'female', 'female', 'male', 'nonbinary', 'male',
    'nonbinary', 'nonbinary', 'nonbinary', 'male',
    'male', 'nonbinary', 'male', 'female',
    'nonbinary', 'nonbinary', 'female', 'nonbinary', 'nonbinary'
]
```

Next, we define the metrics we want to evaluate

-   True positive rate

-   False positive rate

-   Selection rate

-   Count (the number of samples in each group)

We can then create a MetricFrame to calculate these metrics across the data

```{python}
import pandas as pd
pd.set_option('display.max_columns', 20)
pd.set_option('display.width', 80)

from fairlearn.metrics import MetricFrame
from fairlearn.metrics import count, false_positive_rate, selection_rate
from sklearn.metrics import recall_score


my_metrics = {
    'tpr': recall_score,
    'fpr': false_positive_rate,
    'sel': selection_rate,
    'count': count
}

mf = MetricFrame(
    metrics=my_metrics,
    y_true=y_true,
    y_pred=y_pred,
    sensitive_features=sf_data
)

```

The MetricFrame object allows us to easily see the results across all the data using MetricFrame.overall

```{python}
mf.overall
```

We can examine the same metrics for each group using MetricFrame.by_group

```{python}
mf.by_group
```

These disaggregated results make it easier to identify inequality between groups. In this example we can see that females have much lower True positive rate the either males or non-binary people this could be an indication that there is some amount of unfairness in the model.

## Compareing Quantified Harms

After computing metrics for each group the final step in a fairness assessment is to compare the results across groups. We want to see if certain groups experience noticeably higher or lower rates when compared to other groups. A common approach is to use differences or ratios between the groups with the best and worst outcomes. For example, if one group has a much higher true positive rate or a much lower False Positive rate than another group this may indicate a fairness issue in the model.

The Fairlearn library provides several methods that make comparisons easier. We can easily find the minimum and maximum of each metric using the MetricFrame.group_min() and MetricFrame.group_max() functions.

```{python}
mf.group_min()
mf.group_max()
```

We can also find the difference or ratio of the minimum and maximum value of each metric using the MetricFrame.difference() and MetricFrame.ratio() functions

```{python}
mf.difference()
mf.ratio()
```

Each of these methods helps us gain a better understanding of where and to what groups our model may be unfair. If you find great variance in the differences of the maximum and minimum value for a metric in your model it may be a sign that your model is unfair.

## Conclusion

You now know how to use the Fairlearn library to analyze if your model is unfair in four simple steps. First you need to identify what kinds of harm your model can do. Second you have to identify the groups those harms may affect. Third you need to define a metric you will use to measure the harm to a group and Finally compare how the metrics differ between groups. After going through all those steps you should be able to tell if your model is fair or unfair to all users. For further guidance on the capabilities Fairlearn not covered in this guide it is encouraged to go to [Fairlearn API Docs](https://fairlearn.org/v0.13/api_reference/index.html)
